name: finesse
channels:
- conda-forge
dependencies:
  - python=3.14
  - finesse
  - tabulate
  # ifotools for yashwants notebook
  - pip:
    - git+https://gitlab.com/ifosim/ifotools.git@dbb86e36512178b2e02096b8b54311bbfd1e282f

